### PR TITLE
Defining different ways to implement Hyphenopoly alongside Webpack

### PR DESCRIPTION
**Pull request by julian-zatloukal**
As described in #100, I uploaded a demo to _/examples/webpack_ and reference it in the Special use cases section of the documentation. I did also provide a link to a live preview of the demo.

### CODE REVIEW

**Comment by mnater** [comment]
Thank you very much!

**Comment by mnater** [comment]
Sorry, I f*!#d up.

**Comment by mnater** [comment]
Fixed! https://github.com/mnater/Hyphenopoly/pull/103

**Comment by jasperf** [comment]
FYI, just tested the example. I did have to run `npm install` + `npm update` to have `webpack serve --open` work and not hit the error _Class constructor ServeCommand cannot be invoked without 'new'_

**Pull request merged**
